ldcumg/SnapRoad

.github/ISSUE_TEMPLATE/bug-report-template.md, .github/ISSUE_TEMPLATE/feature-request-template.md, .github/PULL_REQUEST_TEMPLATE.md, src/hooks/queries/QueryProvider.tsx
```bash
FEATURE
"[Feat]" - 기능 추가나 개선 사항을 나타낼 때
예: [Feat] 새로운 로그인 기능 추가
ENHANCEMENT
"[Enhan]" - 기존 기능의 개선 사항을 나타낼 때
예: [Enhan] 성능 최적화
"[Fix]" - 버그 수정일 경우
예: [Fix] 로그인 시 발생하는 오류 수정
"[Setup]" - 프로젝트 환경 설정과 관련된 경우
예: [Setup] ESLint 설정 추가
"[Refactor]" - 리팩토링과 관련된 경우
예: [Refactor] 코드 구조 개선
"[Docs]" - 문서 관련 변경 사항일 경우
예: [Docs] README 업데이트
```
> ex) #7
> 이슈 템플릿을 라벨 연결하였습니다.
> 컨벤션에 맞게 PR 템플릿을 수정하였습니다.
>
=> [Docs] 이슈 템플릿 라벨 연결 및 PR 템플릿 수정

src/app/(auth)/login/page.tsx, src/app/(auth)/signup/page.tsx, src/app/page.tsx, src/components/auth/LoginForm.tsx, src/constants/authMessage.ts, src/constants/urls.ts, src/hooks/byUse/useAuthForm.ts, src/hooks/queries/byUse/useAuthMutations.ts, src/schemas/authSchemas.ts, src/services/server-action/authActions.ts
> ex) dee6514e4ba56c028c83935c0c01e05feffcfee2
<br/>
> 로그인/로그아웃
- 로그인 시 존재하지 않는 이메일이면, 존재하지 않는 이메일 alert 
<br/>
- 로그인 한 사용자 정보는 해당 함수로 가져올 수 있습니다.
-> getUser() 는 슈퍼베이스 인증 서버에 네트워크 요청을 수행하여, 사용자 인증을 안전하게 할 수 있다고합니다.
<br/>
> 부족한 점 있으면 말씀부탁드립니다 🥺
=> [feat ]: 로그인/로그아웃

src/app/auth/callback/route.ts, src/components/auth/LoginForm.tsx, src/services/client-action/socialAuthAction.ts, src/services/server-action/authActions.ts
> 4ac6b221bf4f48ccf94bbd02ee485ebd9cfe8777
> 607f688ffa2d9e671e0e2acbf86b4ea80616f82b
> 카카오 구글 로그인 추가하였습니다.
X
X
=> [feat] 소셜로그인(카카오/구글)

package.json, src/app/tour/[tourId]/page.tsx, src/components/auth/LoginForm.tsx, src/components/auth/SignUpForm.tsx, src/components/myPage/PasswordResetForm.tsx, src/components/myPage/Profile.tsx, src/components/tourDetail/Comment.tsx, src/components/tourDetail/CommentForm.tsx, src/components/tourDetail/Comments.tsx, src/components/tourDetail/OptionsMenu.tsx, src/components/tourDetail/TourImages.tsx, src/hooks/queries/byUse/useCommentMutation.ts, src/hooks/queries/byUse/useCommentQueries.ts, src/hooks/queries/byUse/usePostMutation.ts, src/hooks/queries/byUse/useProfilesQueries.ts, src/hooks/queries/byUse/useStorageMutation.ts, src/hooks/queries/byUse/useStorageQueries.ts, src/services/postService.ts, src/services/server-action/commentAction.ts, src/services/server-action/postAction.ts, src/services/server-action/profilesAction.ts, src/types/projectType.ts, src/types/supabaseTypes.ts, src/utils/dateUtils.ts
> 5f59e1f7030bb4c7190bcb580494cc13bcff55b9
> b3beeffe6a584bde65b4edd1d705c7842b0d77b3
> 7ff38edb84d247c11c57cbb8a5f204be069778e3
> b3f17fa9c294c15e57b3c74038692b7f66c2b1a1
> 게시글 상세 페이지 작업
- 게시글 삭제
- 게시글 정보 (이미지, 내용)
- 댓글 대댓글 (CRUD)
=> feat : 게시글 상세 페이지

src/components/groupList/RandomImage.tsx, src/hooks/queries/byUse/useGroupMutations.ts, src/hooks/queries/byUse/useGroupQueries.ts, src/hooks/queries/queryKeys.ts
> eb0e077d5376fd0d4c9f714cf4f752530f2924a4
> 쿼리키분리
> 원빈님 저희 쿼리키관련 상의 내일 필요해보여요~ 오늘은 랜딩쪽 작업하러 가야할거같아요 저는
=> [Refactor] queryKey 분리

src/hooks/queries/byUse/useAuthMutations.ts, src/utils/supabase/middleware.ts
> d224436cd15de9c1e02a3ca8b93a7c01bfc4a808
> 소셜로그인 시 리다이렉트 안되는 문제 수정
=> [Fix] middleware redirect버그 수정

src/components/groupList/RandomImage.tsx
> 아이템 개수에 따라 캐러셀 스타일 수정
> 정말 커스텀스타일 힘드네요
=> [Fix] 캐러셀 스타일 디자인시안대로 수정

src/components/groupList/RandomImage.tsx
> 그룹리스트페이지 랜덤포스트 관련 포스트 이동경로 수정
=> [fix] 포스트 이동경로 수정

src/components/post/postDetail/PostDetail.tsx, src/components/post/postDetail/PostDetailHeader.tsx
> ex) e5c73d1359e09b5b0354a7ddf9caf0d0a8964e30
> 게시글 상세에서 여행 날짜 수정
>
=> fix : 여행날짜 수정

src/components/auth/SocialLogin.tsx
=> style : 소셜로그인 커서 포인터

src/utils/supabase/middleware.ts
> cf74a7c50b016d94ec6e132da40393bd93a78c16
> 로그인시 private 리다이렉트. 랜딩접근시 grouplist 리다이렉트 로직 변경
=> [Hotfix] 미들웨어 로그인시 리다이렉트 로직 변경

src/components/map/GroupMap.tsx
> ex) #7
> 게시물 없을 때 early return 수정
>
=> [Bugfix] 게시물 없을 때 지도 위치 재조정 로직 수정

src/app/group/[groupId]/post/[postId]/page.tsx
> ex)e8b52a68fae3a0f4d559f925f4eb6cf605c8e607
> 게시글 상세에서 로고 클릭시 그룹리스트로 이동
>
=> feat : 게시글 상세에서 Link

src/app/group/[groupId]/page.tsx, src/components/groupAlbum/GroupAlbum.tsx, src/components/groupAlbum/GroupInfoBox.tsx
> ex) #7
> 그룹 앨범 게시물 없을 시 문구 표기
>
=> [Fix] 그룹 앨범 게시물 없을 시 문구 표기

src/app/group/[groupId]/post/[postId]/page.tsx, src/app/mypage/page.tsx, src/components/myPage/MyPageHeader.tsx
> ex) ad7483113835a862f54f5beff0064963915b0bfb
> 게시글 상세에서 그룹 리스트로가는 링크 추가
>
=> feat : 게시글 상세에 링크 추가

src/app/group/[groupId]/page.tsx, src/components/map/GroupMap.tsx
> ex) #7
> 대표이미지에 위도, 경도 없을 시 지도 범위 재설정에서 제외
>
=> [Fix] 대표이미지에 위도, 경도 없을 시 지도 범위 재설정에서 제외

src/app/mypage/edit/page.tsx, src/components/myPage/ProfileUpdate.tsx
>15b1a29049e78e65ce3b1eba349473b65273da26
> 마이페이지 수정 링크 추가 및 높이 조정
>
=> fix : 마이페이지 수정 링크 추가 및 높이 조정

src/components/map/GroupMap.tsx, src/services/server-action/mapAction.ts
- 선택한 위치의 주소가 없을 시 게시물 추가하기 버튼 비활성화
>
=> [Feat] 선택한 위치의 주소가 없을 시 게시물 추가하기 버튼 비활성화

src/app/grouplist/page.tsx, src/components/_common/TopButton.tsx, src/components/groupList/GroupItem.tsx
>bd498689580f0e420759a77122c0bb9d3c6f6f12
> 그룹리스트페이지 이미지 최소크기 변경
=> [Style] 그룹리스트페이지 이미지 최소크기 변경

src/components/map/GroupMap.tsx
```bash
FEATURE
"[Feat]" - 기능 추가나 개선 사항을 나타낼 때
예: [Feat] 새로운 로그인 기능 추가
ENHANCEMENT
"[Enhan]" - 기존 기능의 개선 사항을 나타낼 때
예: [Enhan] 성능 최적화
"[Fix]" - 버그 수정일 경우
예: [Fix] 로그인 시 발생하는 오류 수정
"[Setup]" - 프로젝트 환경 설정과 관련된 경우
예: [Setup] ESLint 설정 추가
"[Refactor]" - 리팩토링과 관련된 경우
예: [Refactor] 코드 구조 개선
"[Docs]" - 문서 관련 변경 사항일 경우
예: [Docs] README 업데이트
```
> ex) #7
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
=> [Fix] 잘못된 커밋 복구

src/components/map/GroupMap.tsx
=> [Fix] 핀, 초기 위도 경도 조정

src/components/makegroup/MakeGroupForm.tsx, src/hooks/queries/byUse/useGroupMutations.ts, src/hooks/queries/byUse/useGroupQueries.ts, src/stories/Spinner.tsx
> 2d3fc8739883349d036d509fa1fca0fa53a7df05
> 그룹생성페이지 로딩 상태에 따라 스피너 렌더링하도록 추가
=> [Style] 그룹생성페이지 로딩 시 스피너 화면에 보이도록 추가

src/components/groupList/GroupAddButton.tsx, src/components/makegroup/MakeGroupForm.tsx, src/hooks/byUse/useGroupForm.ts
> bfac6fefe2a6de5864428bc5b30ee3c34d875b04
> ef213269adfac72599a3af6e4a6d30686fc4a040
> 635a26a7829360fc4c3967c446723db06ed957ce
> 그룹 명 입력관련 그룹 disabled관리, 스타일 변경
=> [Feat] 그룹 리스트 버튼 스타일 변경 및 그룹생성 disabled 유효성검사 추가

src/app/group/[groupId]/layout.tsx
- 게시물 마커 prefetch 적용
- 그룹 상세페이지 그룹명, 그룹 설명 metadata 적용
>
=> [Refactor] 게시물 마커 prefetch

src/app/grouplist/layout.tsx, src/app/page.tsx, src/components/landing/ScrollSections.tsx, src/components/layout/LogoUserHeader.tsx, src/constants/urls.ts, src/utils/supabase/middleware.ts
=> [Refactor] landingpage 피드백 리팩토링

src/constants/buckets.ts, src/services/client-action/groupActions.ts, src/services/server-action/groupServerActions.ts
> 쿼리키처럼 bucketname분리하였습니다.
- /constants/buckets.ts
- /services/groupActions.ts
- 이렇게 사용하시면 됩니다.
=> [Refactor] bucketname 분리

src/components/post/postDetail/CommentNode.tsx, src/components/post/postDetail/PostDetailDesc.tsx, src/components/post/postDetail/ProfileImage.tsx
> 6630e45c0b8aaa0fa6edbffa7a3992100deed77e
>  테일윈드가 인식 못하는 방식으로 하고있었음
조건부 Tailwind 클래스 매핑 방식으로 변경
>
=> fix : 이미지 크기 잘 적용 안되는 문제

package.json, pnpm-lock.yaml, src/components/_common/ImageCropper.tsx, src/components/groupList/GroupItem.tsx, src/components/makegroup/InputSection.tsx, src/components/makegroup/MakeGroupForm.tsx, src/hooks/byUse/useGroupForm.ts, src/schemas/groupSchemas.ts, src/types/CropTypes.ts, src/utils/getCroppedImage.ts
> 그룹 이미지 업로드 후 crop기능 추가
> 리팩토링 전이라 코드 보기 어렵습니다... 기능 리팩토링후에 pr 또 올리고 issue로 사용법 남기겠습니다.
> 너무 어렵네요 자르고 state로 관리하고 그걸 react-hook-form으로 설정하고 어쩌구저쩌구
> 리팩토링하고 추가 pr올릴때 기능사용 관련 정리해서 issue로 남기겠습니다
=> [Feat] 그룹 이미지 crop 기능 추가

src/components/post/postDetail/PostDetailHeader.tsx
> 8a88b3d6ad3199ae00ab220f36badafa7cccee92
게시글 상세에서 옵션 버튼에 미구현된 기능 숨김처리 하였습니다.
- 게시글 삭제
- 게시글 수정
>
=> fix : 미구현 기능 숨김처리

src/constants/urls.ts
=> [Fix] middleware Privateurls 관련 수정

src/constants/urls.ts, src/utils/supabase/middleware.ts
=> [Fix] middlware privateurls 관련 타입 에러 

src/app/group/[groupId]/page.tsx, src/components/map/GroupMap.tsx
> ex) #7
- 게시물 추가하기 버튼 나오게 수정
>
=> [Hotfix] 게시물 추가하기 버튼

src/app/layout.tsx
=> [Fix] ogImage 설정 변경

src/components/map/GroupMap.tsx
=> [Style] 장소 정보 바텀시트 스타일

src/components/map/GroupMap.tsx
> ex) #7
- 대표 이미지의 위도 경도 없을 때도 지도 나타내기
>
=> [Update] 대표 이미지의 위도 경도 없을 때도 지도 나타내기

src/components/makegroup/InputSection.tsx
> 그룹 생성페이지 그룹title placeholder추가
=> [Refactor] 그룹 이름 placeholder추가

src/components/map/GroupMap.tsx, src/stories/BottomSheet.tsx
> ex) #7
- 클러스터 마커에도 바텀시트 이벤트 적용했습니다.
- 잘못 설정한 주석 해제 했습니다.
- 바텀 시트 props 추가한 거 확인해주세요.
=> [Hotfix] 클러스터 마커에 바텀시트 이벤트 적용

src/app/grouplist/layout.tsx, src/components/groupList/RandomImage.tsx, src/components/layout/LogoUserHeader.tsx
> 그룹 리스트 페이지 첫 요청 prefetch적용
> 그룹 리스트가 없을 때 빈 randompost안나타나도록 수정
> 랜덤포스트 이미지 나오지 않는 문제 수정
=> [Refactor] 그룹리스트 페이지 prefetch 적용, 그룹리스트가 없으면 randompost안나타나도록

package.json, pnpm-lock.yaml, src/components/_common/ScrollReactHeader.tsx, src/components/post/EditForms.tsx, src/components/post/PostAddress.tsx, src/components/post/PostDraggable.tsx, src/components/post/PostForms.tsx, src/components/post/PostThumbnail.tsx, src/components/post/postDetail/PostDetailHeader.tsx, src/components/ui/DateInputWithIcon.tsx, src/components/ui/TimeInputWithIcon.tsx, src/hooks/queries/post/useImageHandlersHooks.ts, src/lib/icon/Icon_ Dots.tsx, src/lib/icon/Icon_Arrow_Back_LG.tsx, src/stories/BottomSheet.tsx, src/stories/Modal.tsx
> f95ae4161b205540f3a9bd02c60a9417f7435ac0 a6c40ffa88a379e7dae225c9828e223b70780368 3a27791eb4698a216c54b8fbcf25bbf9d7bc5ab2
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
=> [Fix] 이미지 업로드 후 기존 이미지로 저장 된 부분 refetch로 이미지 최신 상태를 가져와 화면에 반영하기/ 한글 파일명, png,jpg 외의 파일 업로드 불가능 필터링 처리

src/components/post/postDetail/OptionsMenu.tsx, src/components/post/postDetail/PostDetailHeader.tsx, src/hooks/queries/byUse/usePostMutation.ts, src/services/server-action/postAction.ts, src/types/supabaseTypes.ts
> aa444b401402494a9b8fd75b4fc8488c69c6cebd
> 게시글 삭제
삭제시 post 테이블과 image 테이블 둘 다 deleted_at 이 null 로 됨
둘 중 하나라도 실패 시 롤백되어야함 - 수파베이스는 트랜젝션 지원하지 않아서 rpc 로 해결
>
=> [Feat] : 게시글 삭제

src/stories/TopButton.tsx, src/utils/debounce.ts
> topbutton 스크롤 내리면 생기도록 이벤트처리
> 이벤트는 debounce 처리하여 성능문제 방지
=> [Refactor] topbutton 스크롤 내리면 생기도록 디바운스 이벤트 처리

src/app/layout.tsx, src/components/groupAlbum/GroupInfoBox.tsx, src/components/groupList/SubmitInviteForm.tsx, src/components/makegroup/ImagePreview.tsx
> 머지에서 누락된 style 작업 반영
- 그룹인포 파일 확장자 png->jpg 수정하였습니다 @ldcumg 
- ![image](https://github.com/user-attachments/assets/fc8eb705-ede0-45f5-a0fa-cf11f65c3bc5)
=> [Style] 머지 미반영부분 수정

src/components/groupList/GroupItem.tsx, src/components/groupList/GroupList.tsx, src/components/groupList/RandomImage.tsx
> 그룹리스트페이지 pc 반응형 스타일작업
- ![반응](https://github.com/user-attachments/assets/e3490fb4-4cb0-4159-bd25-048ba96a4d64)
=> [Style] 그룹리스트 반응형 작업

src/components/groupAlbum/GroupAlbum.tsx, src/components/groupAlbum/GroupInfoBox.tsx, src/components/makegroup/MakeGroupForm.tsx, src/hooks/queries/byUse/useGroupMutations.ts, src/stories/Modal.tsx
> 그룹 앨범에서 pc 화면일 시 그룹수정 모달 사용하도록 추가
> 그룹 생성/수정 기능 모달에서 사용 시 기능 로딩 spinner가 모달 전체 감싸도록 해야하는데, 대책 강구 필요
=> [Style] 그룹 수정 반응형 디자인

src/app/(auth)/login/error.tsx, src/app/(auth)/signup/error.tsx, src/app/(auth)/signup/page.tsx, src/app/group/[groupId]/post/[postId]/error.tsx, src/app/group/[groupId]/post/[postId]/page.tsx, src/components/auth/LoginForm.tsx, src/components/auth/SignUpForm.tsx, src/components/post/postDetail/CommentForm.tsx, src/components/post/postDetail/CommentNode.tsx, src/components/post/postDetail/CommentUpdateForm.tsx, src/components/post/postDetail/OptionsMenu.tsx, src/components/post/postDetail/PostComment.tsx, src/hooks/byUse/useCommentForm.ts, src/hooks/queries/byUse/useAuthMutations.ts, src/schemas/commentSchemas.ts, src/services/server-action/authActions.ts
> 749fa8e268830548de426958b8353de8f66842e2
- 프로덕션 모드에서 로그인/회원가입 시 예상되는 오류 이상하게 나오던 것 해결
- 댓글 작성 시 입력 안하면 등록 못하도록 막기
- 수정 시 취소버튼 추가
>
=> [fix : 로그인/회원가입시 예상되는 오류처리 변경/댓글 글 작성 안하면 등록못하도록]

src/app/group/[groupId]/post/[postId]/edit/page.tsx, src/app/group/[groupId]/post/page.tsx, src/components/_common/ScrollReactHeader.tsx, src/components/layout/LayoutMain.tsx, src/components/post/PostAddress.tsx, src/components/post/PostForms.tsx, src/components/post/PostPageClient.tsx, src/hooks/byUse/useMediaQuery.ts
> f6e90cc1681caba157e7008241f8013136700d3e f4f4f870c68835b6ee6c3a91dde95271b37d6a39
fix: form 태그에서 발생한 SSR 및 Hydration 오류 해결
- useMediaQuery 훅 수정하여 SSR 환경에서 초기값을 처리
- 서버와 클라이언트의 HTML 불일치 문제로 인한 Hydration 경고 해결
- 최신 API 및 안전한 상태 관리 적용
>
=> [Refactor] postForm PC 레이아웃 부분만 완성(form 태그에서 발생한 SSR 및 Hydration 오류 해결)

src/app/grouplist/layout.tsx, src/components/groupList/SubmitInviteForm.tsx, src/components/layout/LogoUserHeader.tsx
> lighthouse에 따른 aria-label 미비부분 적용하여 접근성 향상
=> [Refactor] 페이지 접근성 향상을 위한 aria-label적용

src/components/groupList/RandomImage.tsx, src/stories/Button.tsx, src/stories/LinkButton.tsx, tailwind.config.ts
> 소형 휴대폰 기준의 반응형 추가
> 소형 호ㅠ대폰에서 버튼이 늘어나는 문제가 있어 해당부분 수정
=> refactor: 버튼 반응형 스타일 추가, 피드백반영

src/app/group/[groupId]/post/[postId]/edit/page.tsx, src/components/post/EditForms.tsx, src/components/post/EditPageClient.tsx, src/components/post/PostForms.tsx, src/components/post/PostPageClient.tsx, src/components/ui/HashtagInput.tsx
> 5cd1872527724dc0e2aebd757e4d8b79c99e4031 a50a66a252723ce2ff62f7778f451f44417108cc
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
=> [Refactor] pc화면 글쓰기 페이지 완료

src/components/auth/LoginForm.tsx, src/components/auth/SignUpForm.tsx, src/components/myPage/Profile.tsx, src/components/post/postDetail/PostDetailHeader.tsx
- 로그인회원가입 버튼에 로딩
- 게시글 상세에 헤더 변경
- 
-
=> style : 반응형 누락 부분

src/app/group/[groupId]/post/[postId]/page.tsx, src/components/post/EditForms.tsx, src/components/post/PostDraggable.tsx, src/components/post/PostForms.tsx, src/components/post/postDetail/OptionsMenu.tsx, src/components/post/postDetail/PostDetailCarousel.tsx, src/components/post/postDetail/PostDetailTitle.tsx
- pc화면 글쓰기 페이지 완료
- pc화면 수정 페이지 완료
- 상세보기 캐러셀 디자인 통일
- 
-
=> [Style] pc 반응형 완료

src/components/map/GroupMap.tsx
=> [Fix] 로직 분리 중 놓친 부분 수정
